version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openpermission-bot
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    # Optionally mount logs directory
    # volumes:
    #   - ./logs:/app/logs
