apiVersion: apps/v1
kind: Deployment
metadata:
  name: openpermission-bot
  labels:
    app: openpermission-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openpermission-bot
  template:
    metadata:
      labels:
        app: openpermission-bot
    spec:
      containers:
      - name: bot
        image: gcr.io/YOUR_PROJECT_ID/openpermission-bot:latest
        env:
        - name: DISCORD_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bot-secrets
              key: token
        - name: CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: discord-bot-secrets
              key: client-id
        - name: GUILD_ID
          valueFrom:
            secretKeyRef:
              name: discord-bot-secrets
              key: guild-id
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "ps aux | grep 'node dist/index.js' | grep -v grep"
          initialDelaySeconds: 30
          periodSeconds: 30
---
apiVersion: v1
kind: Secret
metadata:
  name: discord-bot-secrets
type: Opaque
stringData:
  token: "YOUR_DISCORD_TOKEN"
  client-id: "YOUR_CLIENT_ID"
  guild-id: "YOUR_GUILD_ID"
